---
title: "Figure 3 - Tilemaps"
author: "William Pilcher"
date: "`r Sys.Date()`"
output: 
    html_document:
        toc: true
        toc_float: true
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

# Loading Data and Setting Up Options
```{r init}
source("source/Validation/validation_load_data.R", local = T)
merged <- merged |> subset(cohort == "discovery")

output_corr <- file.path(output, "Indiv_Risk_Signatures", "REVISION2_custom_100524")
dir.create(output_corr, recursive = T, showWarnings = F)
```

# Setup counts object
```{r}
baseline <- merged |> subset(VJ_INTERVAL == "Baseline" & lineage_group != "LQ")
rm(merged)
gc()
```


```{r}
per_pat <- read.csv(file = "/opt/pmedseq-data/wcpilch/Projects/MMRF-ImmuneAtlas-Annotation/data/metadata_1110/mmrf_commpass_IA22_active_standardized_per_patient_20230505.csv", header = T)
per_pat <- per_pat |> dplyr::select(public_id, PROLIF_INDEX)

baseline@meta.data <- baseline@meta.data |> dplyr::left_join(per_pat, by = "public_id")
rownames(baseline@meta.data) <- baseline@meta.data$cellname
# rownames(merged@meta.data) <- merged$cellname
```

# Compute Signatures defined in Supplemental Table 4

```{r}
library(UCell)

signature_list <- c(list(
    "IFN" = c("IFI6", "IFI30", "IFITM3", "IFI44L", "IFITM2", "S100A4", "IFI16", "ISG15", "STAT1", "IFI44", "STAT2", "APOL6", "IFIT3", "IFI35", "IFIT2", "JAK2", "IFI27L2", "GBP1", "GBP2", "IFIT1", "IFIH1", "IFITM1", "GBP4", "IFI27", "ISG15", "MX1", "OAS1", "XAF1", "APOL3", "IFIT5", "IFNG"),
    "IFNA" = c(
        "IFI44L",
        "ISG15",
        "XAF1",
        "IFI6",
        "MX1",
        "LY6E",
        "EIF2AK2",
        "STAT1",
        "MX2",
        "IFIT3",
        "ISG20",
        "OAS1",
        "IFI44",
        "IRF7",
        "IFIT1",
        "OAS3",
        "IFI35",
        "OAS2",
        "IFI27"
    )
))

signature_list <- c(signature_list)
```

```{r}
# tmp <- baseline |> subset(subcluster_V03072023 == "NkT.0")
baseline <- AddModuleScore_UCell(baseline, features = signature_list, name = "")
```


```{r}
baseline@meta.data <- baseline@meta.data |> dplyr::mutate(maf_combined_call = dplyr::case_when(
    maf_call == "yes" | mafa_call == "yes" | mafb_call == "yes" ~ "yes",
    maf_call == "no" & mafa_call == "no" & mafb_call == "no" ~ "no",
    is.na(maf_call) | is.na(mafa_call) | is.na(mafb_call) ~ NA,
    .default = "ERROR"
))

baseline@meta.data <- baseline@meta.data |> dplyr::mutate(nsd2_1q21_multi = dplyr::case_when(
    is.na(nsd2_call) | is.na(seqwgs_cp_1q21_call) ~ NA,
    nsd2_call == "yes" & seqwgs_cp_1q21_call == "yes" ~ "NSD2_1Q",
    nsd2_call == "yes" & seqwgs_cp_1q21_call == "no" ~ "NSD2",
    # maf_combined_call == "yes" & seqwgs_cp_1q21_call == "yes" ~ "MAF+1q21",
    nsd2_call == "no" & seqwgs_cp_1q21_call == "yes" ~ "1Q",
    nsd2_call == "no" & seqwgs_cp_1q21_call == "no" ~ "None",
    .default = "UNHANDLED CASE"
))


table(baseline@meta.data$nsd2_1q21_multi)
table(baseline@meta.data$nsd2_1q21_multi, baseline@meta.data$nsd2_call)
table(baseline@meta.data$nsd2_1q21_multi, baseline@meta.data$seqwgs_cp_1q21_call)
table(baseline@meta.data$nsd2_1q21_multi, baseline@meta.data$IMWG_FLAG_NSD2_AND_1Q21)
```


## Compute a cluster average

```{r}
averageMod <- baseline@meta.data %>%
    dplyr::group_by(lineage_group, public_id) %>%
    dplyr::summarise(
        # "NaiveT" = mean(Naive),
        # "CytotoxicT" = mean(Cytotoxic),
        # "ExhaustedT" = mean(Exhaustion),
        # "DysfunctionalT" = mean(Dysfunctional),
        # "SASP" = mean(SASP),
        "IFN" = mean(IFN),
        "IFNA" = mean(IFNA)

        # "HLA" = mean(HLA)
    ) |>
    gather(Module, Score, -lineage_group, -public_id) |>
    as.data.frame()

diff_expr <- averageMod
```

```{r}
averageMod_immune <- baseline@meta.data %>%
    dplyr::filter(lineage_group != "P" & lineage_group != "LQ") |>
    dplyr::group_by(public_id) %>%
    dplyr::summarise(
        # "NaiveT" = mean(Naive),
        # "CytotoxicT" = mean(Cytotoxic),
        # "ExhaustedT" = mean(Exhaustion),
        # "DysfunctionalT" = mean(Dysfunctional),
        # "SASP" = mean(SASP),
        "IFN" = mean(IFN),
        "IFNA" = mean(IFNA)

        # "HLA" = mean(HLA)
    ) |>
    gather(Module, Score, -public_id) |>
    as.data.frame()

diff_expr_immune <- averageMod_immune
```


```{r}
md_bl <- dplyr::distinct(baseline@meta.data, public_id, davies_based_risk, nsd2_call, maf_combined_call, seqwgs_cp_17p13_call, seqwgs_cp_1q21_call, nsd2_1q21_multi, progression_group)
```

# leftjoin baseline md of risk groups 
# compute average of averages by risk group and cell types
# (Join all these together... will not be one pass)
# 


```{r}
diff_expr <- dplyr::left_join(averageMod, md_bl, by = "public_id", suffix = c("", ".a"))

pat_mean <- averageMod |>
    dplyr::group_by(Module, lineage_group) |>
    dplyr::summarize(mean_module = mean(Score), var_module = var(Score), sd_module = sd(Score))


avg_expr_davies <- diff_expr |>
    dplyr::group_by(lineage_group, Module, davies_based_risk) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::filter(davies_based_risk %in% c("high_risk", "standard_risk")) |>
    dplyr::mutate(factor = paste0("davies_based_risk", "_", davies_based_risk)) |>
    dplyr::select(-davies_based_risk)

avg_expr_nsd2 <- diff_expr |>
    dplyr::group_by(lineage_group, Module, nsd2_call) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::filter(nsd2_call == "yes") |>
    dplyr::mutate(factor = paste0("nsd2_call", "_", nsd2_call)) |>
    dplyr::select(-nsd2_call)

avg_expr_nsd2_1q <- diff_expr |>
    dplyr::group_by(lineage_group, Module, nsd2_1q21_multi) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::mutate(factor = paste0("nsd2_1q21_multi", "_", nsd2_1q21_multi)) |>
    dplyr::select(-nsd2_1q21_multi)


avg_expr_maf <- diff_expr |>
    dplyr::group_by(lineage_group, Module, maf_combined_call) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::filter(maf_combined_call == "yes") |>
    dplyr::mutate(factor = paste0("maf_combined_call", "_", maf_combined_call)) |>
    dplyr::select(-maf_combined_call)

avg_expr_17p13 <- diff_expr |>
    dplyr::group_by(lineage_group, Module, seqwgs_cp_17p13_call) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::filter(seqwgs_cp_17p13_call == "yes") |>
    dplyr::mutate(factor = paste0("seqwgs_cp_17p13_call", "_", seqwgs_cp_17p13_call)) |>
    dplyr::select(-seqwgs_cp_17p13_call)

avg_expr_1q21 <- diff_expr |>
    dplyr::group_by(lineage_group, Module, seqwgs_cp_1q21_call) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::filter(seqwgs_cp_1q21_call == "yes") |>
    dplyr::mutate(factor = paste0("seqwgs_cp_1q21_call", "_", seqwgs_cp_1q21_call)) |>
    dplyr::select(-seqwgs_cp_1q21_call)
```

# Summary Figures

```{r}
all <- rbind(avg_expr_davies, avg_expr_nsd2, avg_expr_maf, avg_expr_17p13, avg_expr_1q21)

all <- all |>
    dplyr::left_join(pat_mean, by = c("Module", "lineage_group")) |>
    group_by(Module, lineage_group) |>
    dplyr::mutate(z = (mean - mean_module) / sd(mean), sd = sd(mean), min_max = 2 * ((mean - min(mean)) / max(mean - min(mean)) - 0.5))

all$factor <- factor(all$factor, levels = rev(unique(all$factor)))

all <- all |> dplyr::mutate(grouping = dplyr::case_when(
    factor %in% c("davies_based_risk_high_risk", "davies_based_risk_standard_risk") ~ "Combined",
    .default = "Individual"
))


df_factor_names <- data.frame(
    factor = c("seqwgs_cp_17p13_call_yes", "maf_combined_call_yes", "seqwgs_cp_1q21_call_yes", "nsd2_call_yes", "davies_based_risk_standard_risk", "davies_based_risk_high_risk"),
    variable_names = c("Del 17p13", "MAF, MAFA, MAFB", "Gain 1q21", "NSD2 t(4;14)", "Standard Risk", "High Risk")
)
all <- dplyr::left_join(all, df_factor_names, by = "factor")
all$variable_names <- factor(all$variable_names, levels = rev(unique(df_factor_names$variable_names)))

all_IFN <- all |> dplyr::filter(Module == "IFNA")

tmp <- diff_expr |>
    dplyr::left_join(pat_mean, by = c("Module", "lineage_group")) |>
    group_by(Module, lineage_group) |>
    dplyr::mutate(z = (Score - mean_module) / sd_module, z_old = (Score - mean_module) / sd(Score), sd_old = sd(Score), min_max = 2 * ((Score - min(Score)) / max(Score - min(Score)) - 0.5))

global_mean <- tmp |>
    group_by(public_id)


PAT_ORDERING <- diff_expr_immune |>
    dplyr::filter(Module == "IFNA") |>
    dplyr::arrange(Score)
global_mean$public_id <- factor(global_mean$public_id, levels = PAT_ORDERING$public_id)

RATIO_PAT_INFO <- 1.5
p <- ggplot(global_mean |> dplyr::filter(Module == "IFNA"), x = public_id, y = lineage_group, fill = z) +
    geom_tile(aes(x = public_id, y = lineage_group, fill = z), color = "#484848", lwd = 0.1, linetype = 1) +
    scale_fill_gradient2(
        low = "#1d9ae3",
        high = "#f63575",
        limits = range(c(-3, 3)),
        oob = squish
    ) +
    theme_prism() +
    xlab("Patient") +
    ylab("Cell Type") +
    theme(
        plot.margin = margin(
            14 / 2, 14 / 2,
            0, 14 / 2
        ),
        axis.text.x = element_blank(),
        plot.title = element_blank(),
        axis.ticks.x = element_blank()
    ) +
    coord_fixed(ratio = 5) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    theme(legend.position = "bottom") +
    scale_y_discrete(expand = c(0, 0))


p_tile_1q21 <- ggplot(global_mean |> dplyr::filter(Module == "IFNA"), x = public_id, y = "Gain 1q21", fill = seqwgs_cp_1q21_call) +
    geom_tile(aes(x = public_id, y = "Gain 1q21", fill = seqwgs_cp_1q21_call), color = "#484848", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_manual(
        values = c("no" = "white", "yes" = "#e48a04")
    ) +
    theme_prism() +
    xlab("Patient") +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))


p_tile_17p13 <- ggplot(global_mean |> dplyr::filter(Module == "IFNA"), x = public_id, y = "Del 17p13", fill = seqwgs_cp_17p13_call) +
    geom_tile(aes(x = public_id, y = "Del 17p13", fill = seqwgs_cp_17p13_call), color = "#484848", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_manual(
        values = c("no" = "white", "yes" = "#009bcf")
    ) +
    theme_prism() +
    xlab("Patient") +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))

p_tile_nsd2 <- ggplot(global_mean |> dplyr::filter(Module == "IFNA"), x = public_id, y = "NSD2 t(4;14)", fill = nsd2_call) +
    geom_tile(aes(x = public_id, y = "NSD2 t(4;14)", fill = nsd2_call), color = "#484848", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_manual(
        values = c("no" = "white", "yes" = "#c32400")
    ) +
    theme_prism() +
    xlab("Patient") +
    ggtitle("IFN-1 Signature Score") +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))

p_tile_maf <- ggplot(global_mean |> dplyr::filter(Module == "IFNA"), x = public_id, y = "MAF, MAFA, MAFB", fill = maf_combined_call) +
    geom_tile(aes(x = public_id, y = "MAF, MAFA, MAFB", fill = maf_combined_call), color = "#484848", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_manual(
        values = c("no" = "white", "yes" = "#00b02c")
    ) +
    theme_prism() +
    xlab("Patient") +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        plot.title = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +
    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))

TEST <- patchwork::wrap_plots(list(p_tile_nsd2, p_tile_1q21, p_tile_maf, p_tile_17p13, p), ncol = 1, nrow = 5)
pdf_and_png(TEST, output_corr, "IFN_plot_pat_with_info", pdfWidth = 12, pdfHeight = 2.7, scale = 2)

p2 <- ggplot(all_IFN |> dplyr::filter(grouping == "Combined"), x = variable_names, y = lineage_group, fill = z) +
    geom_tile(aes(x = variable_names, y = lineage_group, fill = z), color = "black", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_gradient2(
        low = "#1d9ae3",
        high = "#f63575",
        limits = range(c(-1, 1)),
        oob = squish
    ) +
    theme_prism() +
    ylab("") +
    xlab("") +
    theme(
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        plot.margin = margin(
            14 / 2, 14 / 2,
            0, 2
        )
    ) +
    coord_fixed(ratio = 1) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    theme(legend.position = "bottom") +
    scale_y_discrete(expand = c(0, 0))

p3 <- ggplot(all_IFN |> dplyr::filter(grouping == "Individual"), x = variable_names, y = lineage_group, fill = z) +
    geom_tile(aes(x = variable_names, y = lineage_group, fill = z), color = "black", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_gradient2(
        low = "#1d9ae3",
        high = "#f63575",
        limits = range(c(-1, 1)),
        oob = squish
    ) +
    theme_prism() +
    ylab("") +
    xlab("") +
    theme(
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.length.y = unit(0, "lines"),
        plot.margin = margin(
            14 / 2, 14 / 2,
            0, 1
        )
    ) +
    coord_fixed(ratio = 1) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    theme(legend.position = "bottom") +
    scale_y_discrete(expand = c(0, 0))

# TEST <- patchwork::wrap_plots(list(p_tile_nsd2, plot_spacer(), plot_spacer(), p_tile_1q21, plot_spacer(), plot_spacer(), p_tile_maf, plot_spacer(), plot_spacer(), p_tile_17p13,  plot_spacer(),  plot_spacer(), p, p2, p3), ncol = 3, nrow = 5, byrow=TRUE)

# pdf_and_png(TEST, output_corr, "LIKELY_BROKEN", pdfWidth = 12, pdfHeight = 5, scale = 2)

TEST <- patchwork::wrap_plots(list(p2, p3), ncol = 2, nrow = 1)
pdf_and_png(TEST, output_corr, "grouped_per_risk", pdfWidth = 4, pdfHeight = 2.7, scale = 2)


# p2 <- ggplot(all |> dplyr::filter(lineage_group %in% c("CD8", "CD4"), Module %in% c("CytotoxicT", "NaiveT", "ExhaustedT", "DysfunctionalT", "IFN")), x = Module, y = factor, fill = z) +
#     geom_tile(aes(x = Module, y = factor, fill = z), color = "black", lwd = 0.6, linetype = 1) +
#     scale_fill_gradient2(
#         low = "#1d9ae3",
#         high = "#f63575",
#         limits = range(c(-3, 3)),
#         oob = squish
#     ) +
#     facet_grid(grouping ~ lineage_group, scales = "free", space = "free") +
#     theme_prism() +
#     xlab("") +
#     ylab("") +
#     theme(
#         axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
#         plot.margin = margin(
#             14 / 2, 14 / 2,
#             0, 14 / 2
#         ),
#     ) +
#     # element_text(
#     #     angle = 90,
#     #     vjust = 0.5, hjust = 1,
#     # )) +
#     guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white")))



# p3 <- ggplot(all |> dplyr::filter(lineage_group %in% c("CD8", "CD4"), Module %in% c("CytotoxicT", "NaiveT", "ExhaustedT", "DysfunctionalT", "IFN"), factor %in% c("nsd2_call_yes", "seqwgs_cp_1q21_call_yes", "nsd2_1q21_multi_1Q", "nsd2_1q21_multi_NSD2", "nsd2_1q21_multi_NSD2_1Q", "nsd2_1q21_multi_None")), x = Module, y = factor, fill = z) +
#     geom_tile(aes(x = Module, y = factor, fill = z), color = "black", lwd = 0.6, linetype = 1) +
#     scale_fill_gradient2(
#         low = "#1d9ae3",
#         high = "#f63575",
#         limits = range(c(-3, 3)),
#         oob = squish
#     ) +
#     facet_grid(~lineage_group, scales = "free_x", space = "free_x") +
#     theme_prism() +
#     xlab("") +
#     ylab("") +
#     theme(
#         plot.margin = margin(
#             14 / 2, 14 / 2,
#             0, 14 / 2
#         ),
#     ) +
#     # element_text(
#     #     angle = 90,
#     #     vjust = 0.5, hjust = 1,
#     # )) +
#     guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white")))


combined <- patchwork::wrap_plots(list(p, p2), ncol = 2, widths = c(10, 1))

pdf_and_png(p2, output_corr, "IFN_grouping", pdfWidth = 2, pdfHeight = 3, scale = 2)

pdf_and_png(p, output_corr, "IFN_plot_pat", pdfWidth = 8, pdfHeight = 1.8, scale = 2)
pdf_and_png(combined, output_corr, "IFN_plot_pat_combined", pdfWidth = 12, pdfHeight = 3, scale = 2)

# pdf_and_png(p2, output_corr, "T_nk_plot", pdfWidth = 4.5, pdfHeight = 2.5, scale = 2)
# pdf_and_png(p3, output_corr, "T_nk_plot_nsd2_1q_comp", pdfWidth = 12, pdfHeight = 4, scale = 2)
```



```{r}
gene_avg_expr <- AverageExpression(baseline, assays = "RNA", group.by = c("public_id", "lineage_group"), features = c("ISG15", "IFI44L", "MX1", "IFI27", "CCR7", "SELL", "TCF7", "PDCD1", "LAG3", "TOX", "TIGIT", "CTLA4", "FOXP3", "FGFBP2", "GNLY", "PRF1", "GZMH", "B3GAT1", "KLRG1", "ZEB2", "CD69", "CD44", "CD74", "HLA-DPB1", "HLA-DRB1"))$RNA
# colnames(avg_expr) <- gsub("-","_", colnames(avg_expr))
```

```{r}
gene_avg_expr_df <- as.data.frame(gene_avg_expr)
gene_avg_expr_df$gene <- rownames(gene_avg_expr_df)

gene_avg_expr_df <- gene_avg_expr_df |> tidyr::pivot_longer(cols = colnames(gene_avg_expr), names_to = "name", values_to = "Expression")

gene_avg_expr_df <- gene_avg_expr_df |> tidyr::separate(name, sep = "_", c("public_id", "lineage_group")) # dplyr::mutate(public_id = str_split(name, "_")[[1]][1], lineage_group = str_split(name, "_")[[1]][2])
gene_avg_expr_df$public_id <- gsub("-", "_", gene_avg_expr_df$public_id)
gene_avg_expr_df$Module <- gene_avg_expr_df$gene
gene_avg_expr_df$Score <- gene_avg_expr_df$Expression
```

```{r}
diff_expr_avg <- dplyr::left_join(gene_avg_expr_df, md_bl, by = "public_id")

gene_pat_mean <- diff_expr_avg |>
    dplyr::group_by(Module, lineage_group) |>
    dplyr::summarize(mean_module = mean(Score), var_module = var(Score), sd_module = sd(Score))

gene_avg_expr_davies <- diff_expr_avg |>
    dplyr::group_by(lineage_group, Module, davies_based_risk) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::filter(davies_based_risk %in% c("high_risk", "standard_risk")) |>
    dplyr::mutate(factor = paste0("davies_based_risk", "_", davies_based_risk)) |>
    dplyr::select(-davies_based_risk)

gene_avg_expr_nsd2 <- diff_expr_avg |>
    dplyr::group_by(lineage_group, Module, nsd2_call) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::filter(nsd2_call == "yes") |>
    dplyr::mutate(factor = paste0("nsd2_call", "_", nsd2_call)) |>
    dplyr::select(-nsd2_call)


gene_avg_expr_nsd2_1q <- diff_expr_avg |>
    dplyr::group_by(lineage_group, Module, nsd2_1q21_multi) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::mutate(factor = paste0("nsd2_1q21_multi", "_", nsd2_1q21_multi)) |>
    dplyr::select(-nsd2_1q21_multi)


gene_avg_expr_maf <- diff_expr_avg |>
    dplyr::group_by(lineage_group, Module, maf_combined_call) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::filter(maf_combined_call == "yes") |>
    dplyr::mutate(factor = paste0("maf_combined_call", "_", maf_combined_call)) |>
    dplyr::select(-maf_combined_call)

gene_avg_expr_17p13 <- diff_expr_avg |>
    dplyr::group_by(lineage_group, Module, seqwgs_cp_17p13_call) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::filter(seqwgs_cp_17p13_call == "yes") |>
    dplyr::mutate(factor = paste0("seqwgs_cp_17p13_call", "_", seqwgs_cp_17p13_call)) |>
    dplyr::select(-seqwgs_cp_17p13_call)

gene_avg_expr_1q21 <- diff_expr_avg |>
    dplyr::group_by(lineage_group, Module, seqwgs_cp_1q21_call) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::filter(seqwgs_cp_1q21_call == "yes") |>
    dplyr::mutate(factor = paste0("seqwgs_cp_1q21_call", "_", seqwgs_cp_1q21_call)) |>
    dplyr::select(-seqwgs_cp_1q21_call)
```



```{r}
all <- rbind(gene_avg_expr_davies, gene_avg_expr_nsd2, gene_avg_expr_maf, gene_avg_expr_17p13, gene_avg_expr_1q21)

all <- all |>
    dplyr::left_join(gene_pat_mean, by = c("Module", "lineage_group")) |>
    group_by(Module, lineage_group) |>
    dplyr::mutate(z = (mean - mean_module) / sd_module, z_old = (mean - mean_module) / sd(mean), sd_old = sd(mean), min_max = 2 * ((mean - min(mean)) / max(mean - min(mean)) - 0.5))

all$factor <- factor(all$factor, levels = rev(unique(all$factor)))

all <- all |> dplyr::mutate(grouping = dplyr::case_when(
    factor %in% c("davies_based_risk_high_risk", "davies_based_risk_standard_risk") ~ "Combined",
    .default = "Individual"
))


df_factor_names <- data.frame(
    factor = c("seqwgs_cp_17p13_call_yes", "maf_combined_call_yes", "seqwgs_cp_1q21_call_yes", "nsd2_call_yes", "davies_based_risk_standard_risk", "davies_based_risk_high_risk"),
    variable_names = c("Del 17p13", "MAF, MAFA, MAFB", "Gain 1q21", "NSD2 t(4;14)", "Standard Risk", "High Risk")
)
all <- dplyr::left_join(all, df_factor_names, by = "factor")
all$variable_names <- factor(all$variable_names, levels = rev(unique(df_factor_names$variable_names)))

all_IFN <- all |> dplyr::filter(Module == "IFNA")

tmp <- diff_expr_avg |>
    dplyr::left_join(gene_pat_mean, by = c("Module", "lineage_group")) |>
    group_by(Module, lineage_group) |>
    dplyr::mutate(z = (Score - mean_module) / sd_module, z_old = (Score - mean_module) / sd(Score), min_max = 2 * ((Score - min(Score)) / max(Score - min(Score)) - 0.5))

global_mean <- tmp |>
    dplyr::filter(lineage_group == "CD8") |>
    group_by(public_id)


PAT_ORDERING <- diff_expr |>
    dplyr::filter(Module == "CytotoxicT", lineage_group == "CD8") |>
    dplyr::arrange(Score)

PAT_ORDERING <- PAT_ORDERING |>
    dplyr::left_join(pat_mean, by = c("Module", "lineage_group")) |>
    group_by(Module, lineage_group) |>
    dplyr::mutate(z = (Score - mean_module) / sd(Score), min_max = 2 * ((Score - min(Score)) / max(Score - min(Score)) - 0.5))


global_mean$public_id <- factor(global_mean$public_id, levels = PAT_ORDERING$public_id)
PAT_ORDERING$public_id <- factor(PAT_ORDERING$public_id, levels = PAT_ORDERING$public_id)

global_mean <- global_mean |> dplyr::filter(progression_group %in% c("RP", "NP"))
PAT_ORDERING <- PAT_ORDERING |> dplyr::filter(progression_group %in% c("RP", "NP"))

RATIO_PAT_INFO <- 1.5
p <- ggplot(global_mean |> dplyr::filter(Module %in% c("FGFBP2", "GNLY", "GZMH", "PRF1", "B3GAT1", "KLRG1", "ZEB2")), x = public_id, y = Module, fill = z) +
    geom_tile(aes(x = public_id, y = Module, fill = z), color = "#484848", lwd = 0.1, linetype = 1) +
    scale_fill_gradient2(
        low = "#1d9ae3",
        high = "#f63575",
        limits = range(c(-3, 3)),
        oob = squish
    ) +
    theme_prism() +
    xlab("Patient") +
    ylab("Gene") +
    theme(
        plot.margin = margin(
            14 / 2, 14 / 2,
            0, 14 / 2
        ),
        axis.text.x = element_blank(),
        plot.title = element_blank(),
        axis.ticks.x = element_blank()
    ) +
    coord_fixed(ratio = 5) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    theme(legend.position = "bottom") +
    scale_y_discrete(expand = c(0, 0))

p_sig <- ggplot(PAT_ORDERING, x = public_id, y = Score, fill = z) +
    geom_tile(aes(x = public_id, y = Score, fill = z), color = "#484848", lwd = 0.1, linetype = 1) +
    scale_fill_gradient2(
        low = "#1d9ae3",
        high = "#f63575",
        limits = range(c(-3, 3)),
        oob = squish
    ) +
    theme_prism() +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))


p_tile_1q21 <- ggplot(global_mean, x = public_id, y = "Gain 1q21", fill = seqwgs_cp_1q21_call) +
    geom_tile(aes(x = public_id, y = "Gain 1q21", fill = seqwgs_cp_1q21_call), color = "#484848", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_manual(
        values = c("no" = "white", "yes" = "#e48a04")
    ) +
    theme_prism() +
    xlab("Patient") +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))


p_tile_17p13 <- ggplot(global_mean, x = public_id, y = "Del 17p13", fill = seqwgs_cp_17p13_call) +
    geom_tile(aes(x = public_id, y = "Del 17p13", fill = seqwgs_cp_17p13_call), color = "#484848", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_manual(
        values = c("no" = "white", "yes" = "#009bcf")
    ) +
    theme_prism() +
    xlab("Patient") +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))

p_tile_nsd2 <- ggplot(global_mean, x = public_id, y = "NSD2 t(4;14)", fill = nsd2_call) +
    geom_tile(aes(x = public_id, y = "NSD2 t(4;14)", fill = nsd2_call), color = "#484848", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_manual(
        values = c("no" = "white", "yes" = "#c32400")
    ) +
    theme_prism() +
    xlab("Patient") +
    ggtitle("IFN-1 Signature Score") +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))

p_tile_maf <- ggplot(global_mean, x = public_id, y = "MAF, MAFA, MAFB", fill = maf_combined_call) +
    geom_tile(aes(x = public_id, y = "MAF, MAFA, MAFB", fill = maf_combined_call), color = "#484848", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_manual(
        values = c("no" = "white", "yes" = "#00b02c")
    ) +
    theme_prism() +
    xlab("Patient") +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        plot.title = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +
    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))

TEST <- patchwork::wrap_plots(list(p_tile_nsd2, p_tile_1q21, p_tile_maf, p_tile_17p13, p_sig, p), ncol = 1, nrow = 6)
pdf_and_png(TEST, output_corr, "CYTO_GENE_PLOT", pdfWidth = 12, pdfHeight = 2.7, scale = 2)
```


```{r}
all <- rbind(gene_avg_expr_davies, gene_avg_expr_nsd2, gene_avg_expr_maf, gene_avg_expr_17p13, gene_avg_expr_1q21)

all <- all |>
    dplyr::left_join(gene_pat_mean, by = c("Module", "lineage_group")) |>
    group_by(Module, lineage_group) |>
    dplyr::mutate(z = (mean - mean_module) / sd_module, z_old = (mean - mean_module) / sd(mean), min_max = 2 * ((mean - min(mean)) / max(mean - min(mean)) - 0.5))

all$factor <- factor(all$factor, levels = rev(unique(all$factor)))

all <- all |> dplyr::mutate(grouping = dplyr::case_when(
    factor %in% c("davies_based_risk_high_risk", "davies_based_risk_standard_risk") ~ "Combined",
    .default = "Individual"
))


df_factor_names <- data.frame(
    factor = c("seqwgs_cp_17p13_call_yes", "maf_combined_call_yes", "seqwgs_cp_1q21_call_yes", "nsd2_call_yes", "davies_based_risk_standard_risk", "davies_based_risk_high_risk"),
    variable_names = c("Del 17p13", "MAF, MAFA, MAFB", "Gain 1q21", "NSD2 t(4;14)", "Standard Risk", "High Risk")
)
all <- dplyr::left_join(all, df_factor_names, by = "factor")
all$variable_names <- factor(all$variable_names, levels = rev(unique(df_factor_names$variable_names)))

all_IFN <- all |> dplyr::filter(Module == "IFNA")

tmp <- diff_expr_avg |>
    dplyr::left_join(gene_pat_mean, by = c("Module", "lineage_group")) |>
    group_by(Module, lineage_group) |>
    dplyr::mutate(z = (Score - mean_module) / sd_module, z_old = (Score - mean_module) / sd(Score), min_max = 2 * ((Score - min(Score)) / max(Score - min(Score)) - 0.5))

global_mean <- tmp |>
    dplyr::filter(lineage_group == "CD8") |>
    group_by(public_id)


PAT_ORDERING <- diff_expr |>
    dplyr::filter(Module == "ExhaustedT", lineage_group == "CD8") |>
    dplyr::arrange(Score)

PAT_ORDERING <- PAT_ORDERING |>
    dplyr::left_join(pat_mean, by = c("Module", "lineage_group")) |>
    group_by(Module, lineage_group) |>
    dplyr::mutate(z = (Score - mean_module) / sd(Score), min_max = 2 * ((Score - min(Score)) / max(Score - min(Score)) - 0.5))


global_mean$public_id <- factor(global_mean$public_id, levels = PAT_ORDERING$public_id)
PAT_ORDERING$public_id <- factor(PAT_ORDERING$public_id, levels = PAT_ORDERING$public_id)

RATIO_PAT_INFO <- 1.5
p <- ggplot(global_mean |> dplyr::filter(Module %in% c("LAG3", "TIGIT", "TOX", "PDCD1")), x = public_id, y = Module, fill = z) +
    geom_tile(aes(x = public_id, y = Module, fill = z), color = "#484848", lwd = 0.1, linetype = 1) +
    scale_fill_gradient2(
        low = "#1d9ae3",
        high = "#f63575",
        limits = range(c(-3, 3)),
        oob = squish
    ) +
    theme_prism() +
    xlab("Patient") +
    ylab("Gene") +
    theme(
        plot.margin = margin(
            14 / 2, 14 / 2,
            0, 14 / 2
        ),
        axis.text.x = element_blank(),
        plot.title = element_blank(),
        axis.ticks.x = element_blank()
    ) +
    coord_fixed(ratio = 5) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    theme(legend.position = "bottom") +
    scale_y_discrete(expand = c(0, 0))

p_sig <- ggplot(PAT_ORDERING, x = public_id, y = Score, fill = z) +
    geom_tile(aes(x = public_id, y = Score, fill = z), color = "#484848", lwd = 0.1, linetype = 1) +
    scale_fill_gradient2(
        low = "#1d9ae3",
        high = "#f63575",
        limits = range(c(-3, 3)),
        oob = squish
    ) +
    theme_prism() +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))


p_tile_1q21 <- ggplot(global_mean, x = public_id, y = "Gain 1q21", fill = seqwgs_cp_1q21_call) +
    geom_tile(aes(x = public_id, y = "Gain 1q21", fill = seqwgs_cp_1q21_call), color = "#484848", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_manual(
        values = c("no" = "white", "yes" = "#e48a04")
    ) +
    theme_prism() +
    xlab("Patient") +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))


p_tile_17p13 <- ggplot(global_mean, x = public_id, y = "Del 17p13", fill = seqwgs_cp_17p13_call) +
    geom_tile(aes(x = public_id, y = "Del 17p13", fill = seqwgs_cp_17p13_call), color = "#484848", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_manual(
        values = c("no" = "white", "yes" = "#009bcf")
    ) +
    theme_prism() +
    xlab("Patient") +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))

p_tile_nsd2 <- ggplot(global_mean, x = public_id, y = "NSD2 t(4;14)", fill = nsd2_call) +
    geom_tile(aes(x = public_id, y = "NSD2 t(4;14)", fill = nsd2_call), color = "#484848", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_manual(
        values = c("no" = "white", "yes" = "#c32400")
    ) +
    theme_prism() +
    xlab("Patient") +
    ggtitle("IFN-1 Signature Score") +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))

p_tile_maf <- ggplot(global_mean, x = public_id, y = "MAF, MAFA, MAFB", fill = maf_combined_call) +
    geom_tile(aes(x = public_id, y = "MAF, MAFA, MAFB", fill = maf_combined_call), color = "#484848", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_manual(
        values = c("no" = "white", "yes" = "#00b02c")
    ) +
    theme_prism() +
    xlab("Patient") +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        plot.title = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +
    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))

TEST <- patchwork::wrap_plots(list(p_tile_nsd2, p_tile_1q21, p_tile_maf, p_tile_17p13, p_sig, p), ncol = 1, nrow = 6)
pdf_and_png(TEST, output_corr, "CYTOTOX_GENE_PLOT", pdfWidth = 12, pdfHeight = 2.7, scale = 2)
```



```{r}
all <- rbind(gene_avg_expr_davies, gene_avg_expr_nsd2, gene_avg_expr_maf, gene_avg_expr_17p13, gene_avg_expr_1q21)

all <- all |>
    dplyr::left_join(gene_pat_mean, by = c("Module", "lineage_group")) |>
    group_by(Module, lineage_group) |>
    dplyr::mutate(z = (mean - mean_module) / sd(mean), min_max = 2 * ((mean - min(mean)) / max(mean - min(mean)) - 0.5))

all$factor <- factor(all$factor, levels = rev(unique(all$factor)))

all <- all |> dplyr::mutate(grouping = dplyr::case_when(
    factor %in% c("davies_based_risk_high_risk", "davies_based_risk_standard_risk") ~ "Combined",
    .default = "Individual"
))


df_factor_names <- data.frame(
    factor = c("seqwgs_cp_17p13_call_yes", "maf_combined_call_yes", "seqwgs_cp_1q21_call_yes", "nsd2_call_yes", "davies_based_risk_standard_risk", "davies_based_risk_high_risk"),
    variable_names = c("Del 17p13", "MAF, MAFA, MAFB", "Gain 1q21", "NSD2 t(4;14)", "Standard Risk", "High Risk")
)
all <- dplyr::left_join(all, df_factor_names, by = "factor")
all$variable_names <- factor(all$variable_names, levels = rev(unique(df_factor_names$variable_names)))

all_IFN <- all |> dplyr::filter(Module == "IFNA")

tmp <- diff_expr_avg |>
    dplyr::left_join(gene_pat_mean, by = c("Module", "lineage_group")) |>
    group_by(Module, lineage_group) |>
    dplyr::mutate(z = (Score - mean_module) / sd(Score), min_max = 2 * ((Score - min(Score)) / max(Score - min(Score)) - 0.5))

global_mean <- tmp |>
    dplyr::filter(lineage_group == "CD4") |>
    group_by(public_id)


PAT_ORDERING <- diff_expr |>
    dplyr::filter(Module == "ExhaustedT", lineage_group == "CD4") |>
    dplyr::arrange(Score)

PAT_ORDERING <- PAT_ORDERING |>
    dplyr::left_join(pat_mean, by = c("Module", "lineage_group")) |>
    group_by(Module, lineage_group) |>
    dplyr::mutate(z = (Score - mean_module) / sd(Score), min_max = 2 * ((Score - min(Score)) / max(Score - min(Score)) - 0.5))


global_mean$public_id <- factor(global_mean$public_id, levels = PAT_ORDERING$public_id)
PAT_ORDERING$public_id <- factor(PAT_ORDERING$public_id, levels = PAT_ORDERING$public_id)

RATIO_PAT_INFO <- 1.5
p <- ggplot(global_mean |> dplyr::filter(Module %in% c("LAG3", "TIGIT", "TOX", "PDCD1", "FOXP3", "CTLA4")), x = public_id, y = Module, fill = z) +
    geom_tile(aes(x = public_id, y = Module, fill = z), color = "#484848", lwd = 0.1, linetype = 1) +
    scale_fill_gradient2(
        low = "#1d9ae3",
        high = "#f63575",
        limits = range(c(-3, 3)),
        oob = squish
    ) +
    theme_prism() +
    xlab("Patient") +
    ylab("Gene") +
    theme(
        plot.margin = margin(
            14 / 2, 14 / 2,
            0, 14 / 2
        ),
        axis.text.x = element_blank(),
        plot.title = element_blank(),
        axis.ticks.x = element_blank()
    ) +
    coord_fixed(ratio = 5) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    theme(legend.position = "bottom") +
    scale_y_discrete(expand = c(0, 0))

p_sig <- ggplot(PAT_ORDERING, x = public_id, y = Score, fill = z) +
    geom_tile(aes(x = public_id, y = Score, fill = z), color = "#484848", lwd = 0.1, linetype = 1) +
    scale_fill_gradient2(
        low = "#1d9ae3",
        high = "#f63575",
        limits = range(c(-3, 3)),
        oob = squish
    ) +
    theme_prism() +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))


p_tile_1q21 <- ggplot(global_mean, x = public_id, y = "Gain 1q21", fill = seqwgs_cp_1q21_call) +
    geom_tile(aes(x = public_id, y = "Gain 1q21", fill = seqwgs_cp_1q21_call), color = "#484848", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_manual(
        values = c("no" = "white", "yes" = "#e48a04")
    ) +
    theme_prism() +
    xlab("Patient") +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))


p_tile_17p13 <- ggplot(global_mean, x = public_id, y = "Del 17p13", fill = seqwgs_cp_17p13_call) +
    geom_tile(aes(x = public_id, y = "Del 17p13", fill = seqwgs_cp_17p13_call), color = "#484848", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_manual(
        values = c("no" = "white", "yes" = "#009bcf")
    ) +
    theme_prism() +
    xlab("Patient") +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))

p_tile_nsd2 <- ggplot(global_mean, x = public_id, y = "NSD2 t(4;14)", fill = nsd2_call) +
    geom_tile(aes(x = public_id, y = "NSD2 t(4;14)", fill = nsd2_call), color = "#484848", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_manual(
        values = c("no" = "white", "yes" = "#c32400")
    ) +
    theme_prism() +
    xlab("Patient") +
    ggtitle("IFN-1 Signature Score") +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +

    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))

p_tile_maf <- ggplot(global_mean, x = public_id, y = "MAF, MAFA, MAFB", fill = maf_combined_call) +
    geom_tile(aes(x = public_id, y = "MAF, MAFA, MAFB", fill = maf_combined_call), color = "#484848", lwd = 0.1, linetype = 1, show.legend = FALSE) +
    scale_fill_manual(
        values = c("no" = "white", "yes" = "#00b02c")
    ) +
    theme_prism() +
    xlab("Patient") +
    theme(
        plot.margin = margin(
            0, 0,
            0, 0
        ),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.length.x = unit(0, "lines"),
        plot.title = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    ) +
    coord_fixed(ratio = RATIO_PAT_INFO) +
    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    scale_y_discrete(expand = c(0, 0))

TEST <- patchwork::wrap_plots(list(p_tile_nsd2, p_tile_1q21, p_tile_maf, p_tile_17p13, p_sig, p), ncol = 1, nrow = 6)
pdf_and_png(TEST, output_corr, "CD4_EXH_GENE_PLOT", pdfWidth = 12, pdfHeight = 2.7, scale = 2)
```



```{r}
output_rds <- file.path("output", "BulkRNA_misc_GSVA", "GSVA_IFN.rds")
IFN_bulk <- readRDS(output_rds)

IFN_bulk_filt <- IFN_bulk |> dplyr::select(public_id, IFN_Score)
```


```{r}
gene_avg_expr <- AverageExpression(baseline, assays = "RNA", group.by = c("public_id", "lineage_group"), features = c("ISG15", "IFI44L", "MX1", "IFI27", "CCR7", "SELL", "TCF7", "PDCD1", "LAG3", "TOX", "TIGIT", "CTLA4", "FOXP3", "FGFBP2", "GNLY", "PRF1", "GZMH", "B3GAT1", "KLRG1", "ZEB2", "CD69", "CD44", "CD74", "HLA-DPB1", "HLA-DRB1"))$RNA
# colnames(avg_expr) <- gsub("-","_", colnames(avg_expr))
```

```{r}
gene_avg_expr_df <- as.data.frame(gene_avg_expr)
gene_avg_expr_df$gene <- rownames(gene_avg_expr_df)

gene_avg_expr_df <- gene_avg_expr_df |> tidyr::pivot_longer(cols = colnames(gene_avg_expr), names_to = "name", values_to = "Expression")

gene_avg_expr_df <- gene_avg_expr_df |> tidyr::separate(name, sep = "_", c("public_id", "lineage_group")) # dplyr::mutate(public_id = str_split(name, "_")[[1]][1], lineage_group = str_split(name, "_")[[1]][2])
gene_avg_expr_df$public_id <- gsub("-", "_", gene_avg_expr_df$public_id)
gene_avg_expr_df$Module <- gene_avg_expr_df$gene
gene_avg_expr_df$Score <- gene_avg_expr_df$Expression
```

```{r}
diff_expr_avg <- dplyr::left_join(gene_avg_expr_df, md_bl, by = "public_id")

gene_pat_mean <- diff_expr_avg |>
    dplyr::group_by(Module, lineage_group) |>
    dplyr::summarize(mean_module = mean(Score), var_module = var(Score))

gene_avg_expr_davies <- diff_expr_avg |>
    dplyr::group_by(lineage_group, Module, davies_based_risk) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::filter(davies_based_risk %in% c("high_risk", "standard_risk")) |>
    dplyr::mutate(factor = paste0("davies_based_risk", "_", davies_based_risk)) |>
    dplyr::select(-davies_based_risk)

gene_avg_expr_nsd2 <- diff_expr_avg |>
    dplyr::group_by(lineage_group, Module, nsd2_call) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::filter(nsd2_call == "yes") |>
    dplyr::mutate(factor = paste0("nsd2_call", "_", nsd2_call)) |>
    dplyr::select(-nsd2_call)


gene_avg_expr_nsd2_1q <- diff_expr_avg |>
    dplyr::group_by(lineage_group, Module, nsd2_1q21_multi) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::mutate(factor = paste0("nsd2_1q21_multi", "_", nsd2_1q21_multi)) |>
    dplyr::select(-nsd2_1q21_multi)


gene_avg_expr_maf <- diff_expr_avg |>
    dplyr::group_by(lineage_group, Module, maf_combined_call) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::filter(maf_combined_call == "yes") |>
    dplyr::mutate(factor = paste0("maf_combined_call", "_", maf_combined_call)) |>
    dplyr::select(-maf_combined_call)

gene_avg_expr_17p13 <- diff_expr_avg |>
    dplyr::group_by(lineage_group, Module, seqwgs_cp_17p13_call) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::filter(seqwgs_cp_17p13_call == "yes") |>
    dplyr::mutate(factor = paste0("seqwgs_cp_17p13_call", "_", seqwgs_cp_17p13_call)) |>
    dplyr::select(-seqwgs_cp_17p13_call)

gene_avg_expr_1q21 <- diff_expr_avg |>
    dplyr::group_by(lineage_group, Module, seqwgs_cp_1q21_call) |>
    dplyr::summarise(mean = mean(Score)) |>
    dplyr::filter(seqwgs_cp_1q21_call == "yes") |>
    dplyr::mutate(factor = paste0("seqwgs_cp_1q21_call", "_", seqwgs_cp_1q21_call)) |>
    dplyr::select(-seqwgs_cp_1q21_call)
```

# Figure 3B summary plot
```{r}
all <- rbind(gene_avg_expr_davies, gene_avg_expr_nsd2, gene_avg_expr_maf, gene_avg_expr_17p13, gene_avg_expr_1q21)

all <- all |>
    dplyr::left_join(gene_pat_mean, by = c("Module", "lineage_group")) |>
    group_by(Module, lineage_group) |>
    dplyr::mutate(z = (mean - mean_module) / sd_module, z_old = (mean - mean_module) / sd(mean), min_max = 2 * ((mean - min(mean)) / max(mean - min(mean)) - 0.5))

df_factor_names <- data.frame(
    factor = c("seqwgs_cp_17p13_call_yes", "maf_combined_call_yes", "seqwgs_cp_1q21_call_yes", "nsd2_call_yes", "davies_based_risk_standard_risk", "davies_based_risk_high_risk"),
    variable_names = c("Del 17p13", "MAF, MAFA, MAFB", "Gain 1q21", "NSD2 t(4;14)", "Standard Risk", "High Risk")
)


df_gene_groupings <- data.frame(
    Module = c("ISG15", "IFI44L", "MX1", "IFI27", "CCR7", "SELL", "TCF7", "CD69", "CD44", "CD74", "PDCD1", "LAG3", "TOX", "TIGIT", "CTLA4", "FOXP3", "HLA-DPB1", "HLA-DRB1", "FGFBP2", "GNLY", "PRF1", "GZMH", "B3GAT1", "KLRG1", "ZEB2"),
    gene_grouping = c("IFN-1", "IFN-1", "IFN-1", "IFN-1", "Naive", "Naive", "Naive", "Activation", "Activation", "Activation", "Exhaustion", "Exhaustion", "Exhaustion", "Exhaustion", "T-Reg", "T-Reg", "MHC-II", "MHC-II", "Cytotoxicity", "Cytotoxicity", "Cytotoxicity", "Cytotoxicity", "Senescence", "Senescence", "Senescence")
)

gene_grouping_ordering <- unique(df_gene_groupings$gene_grouping)

all <- dplyr::left_join(all, df_factor_names, by = "factor") |>
    dplyr::left_join(df_gene_groupings, by = "Module") |>
    dplyr::arrange(factor)
all$variable_names <- factor(all$variable_names, levels = (unique(df_factor_names$variable_names)))

all$factor <- factor(all$factor, levels = (unique(df_factor_names$factor)))
all$Module <- factor(all$Module, levels = (unique(all$Module)))
all$gene_grouping <- factor(all$gene_grouping, levels = (unique(gene_grouping_ordering)))




all_filt <- all |> dplyr::filter(lineage_group %in% c("CD8"), Module %in% c("ISG15", "IFI44L", "MX1", "IFI27", "CCR7", "SELL", "TCF7", "PDCD1", "LAG3", "TOX", "TIGIT", "FGFBP2", "GNLY", "PRF1", "GZMH", "B3GAT1", "KLRG1", "ZEB2", "CD69", "CD44", "CD74", "HLA-DPB1", "HLA-DRB1"))



all_filt$Module <- factor(all_filt$Module, levels = c("ISG15", "IFI44L", "MX1", "IFI27", "CCR7", "SELL", "TCF7", "CD69", "CD44", "CD74", "PDCD1", "LAG3", "TOX", "TIGIT", "HLA-DPB1", "HLA-DRB1", "FGFBP2", "GNLY", "PRF1", "GZMH", "B3GAT1", "KLRG1", "ZEB2"))



all_filt <- all_filt |> dplyr::mutate(grouping = dplyr::case_when(
    factor %in% c("davies_based_risk_high_risk", "davies_based_risk_standard_risk") ~ "Combined",
    .default = "Individual"
))

p1 <- ggplot(all_filt, x = Module, y = variable_names, fill = z) +
    geom_tile(aes(x = Module, y = variable_names, fill = z), color = "black", lwd = 0.6, linetype = 1) +
    scale_fill_gradient2(
        low = "#1d9ae3",
        high = "#f63575",
        limits = range(c(-1, 1)),
        oob = squish
    ) +
    theme_prism() +
    facet_grid(grouping ~ gene_grouping, space = "free", scales = "free") +
    xlab("") +
    ylab("") +
    theme(
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        plot.margin = margin(
            14 / 2, 14 / 2,
            0, 14 / 2
        ),
        panel.spacing.x = unit(0.25, "lines"),
        strip.text.y = element_blank()
    ) +
    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    theme(legend.position = "bottom", legend.margin = margin(0, 0, 0, 0), legend.box.margin = margin(0, 0, 0, 0))

pdf_and_png(p1, output_corr, "T_nk_plotb_gene", pdfWidth = W_FULL * 1.5, pdfHeight = H_FULL * .65, scale = 2.5)

all_filt <- all |> dplyr::filter(lineage_group %in% c("CD4"), Module %in% c("ISG15", "IFI44L", "MX1", "IFI27", "CCR7", "SELL", "TCF7", "PDCD1", "LAG3", "TOX", "TIGIT", "CTLA4", "FOXP3", "FGFBP2", "GNLY", "PRF1", "GZMH", "B3GAT1", "KLRG1", "ZEB2", "CD69", "CD44", "CD74"))

all_filt$Module <- factor(all_filt$Module, levels = c("ISG15", "IFI44L", "MX1", "IFI27", "CCR7", "SELL", "TCF7", "CD69", "CD44", "CD74", "PDCD1", "LAG3", "TOX", "TIGIT", "CTLA4", "FOXP3", "FGFBP2", "GNLY", "PRF1", "GZMH", "B3GAT1", "KLRG1", "ZEB2"))

all_filt <- all_filt |> dplyr::mutate(grouping = dplyr::case_when(
    factor %in% c("davies_based_risk_high_risk", "davies_based_risk_standard_risk") ~ "Combined",
    .default = "Individual"
))

p2 <- ggplot(all_filt, x = Module, y = variable_names, fill = z) +
    geom_tile(aes(x = Module, y = variable_names, fill = z), color = "black", lwd = 0.6, linetype = 1) +
    scale_fill_gradient2(
        low = "#1d9ae3",
        high = "#f63575",
        limits = range(c(-1, 1)),
        oob = squish
    ) +
    theme_prism() +
    facet_grid(grouping ~ gene_grouping, space = "free", scales = "free") +
    xlab("") +
    ylab("") +
    theme(
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        plot.margin = margin(
            14 / 2, 14 / 2,
            0, 14 / 2
        ),
        panel.spacing.x = unit(0.25, "lines"),
        strip.text.y = element_blank()
    ) +
    # element_text(
    #     angle = 90,
    #     vjust = 0.5, hjust = 1,
    # )) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white"))) +
    theme(legend.position = "bottom", legend.margin = margin(0, 0, 0, 0), legend.box.margin = margin(0, 0, 0, 0))





pdf_and_png(p2, output_corr, "T_nk_plotb_gene_cd4", pdfWidth = W_FULL * 1.5, pdfHeight = H_FULL * .65, scale = 2.5)

combined <- patchwork::wrap_plots(list(p2, p1), ncol = 2)

pdf_and_png(combined, output_corr, "cd4_cd8_combined", pdfWidth = W_FULL * 3, pdfHeight = H_FULL * .7, scale = 3)
```