---
title: "Figure 4 - Trajectory Visualization"
author: "William Pilcher"
date: "`r Sys.Date()`"
output: 
    html_document:
        toc: true
        toc_float: true
---

Renders visuals for the CD8+ Trajectory Analysis in Figure 4 (4I, 4J, 4K)

```{r setup, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

# Setup - Load Trajectory Object
```{r init}
source("source/Validation/validation_load_data.R", local = T)

cd8_seurat <- merged |> subset(lineage_group == "CD8")

per_cell_cluster_info <- cd8_seurat@meta.data |> dplyr::select(subcluster_V03072023, cellname, color_sub, primary_id_color, color, cellID_short)

cluster_size <- per_cell_cluster_info$subcluster_V03072023 |>
    table() |>
    as.data.frame()
colnames(cluster_size) <- c("Cluster", "Cell Count")

per_cluster_info <- cd8_seurat@meta.data |> dplyr::distinct(subcluster_V03072023, color_sub, primary_id_color, color, cellID_short)

sce_path <- "/opt/pmedseq-data/wcpilch/Projects/MMRF-ImmuneAtlas-Annotation/output/monocle3_cd8_LQ_included/slingshot_cd8_NEWMD_25/sce_slingshot_cd8_NEWMD_25.rds"
sce <- readRDS(sce_path)

output_traj <- file.path(output, "Individual_Risk", "Trajectory")
dir.create(output_traj, showWarnings = F, recursive = T)
```

# Figure 4I - Setup UMAP Rendering

```{r}
set.seed(42)
library("igraph")
library(slingshot)
object_MST <- slingMST(sce)
edgelist <- as.directed(object_MST)
coords <- igraph::layout_with_fr(object_MST) |> as.data.frame()
colnames(coords) <- c("X", "Y")
coords$Cluster <- names(object_MST[2])
rownames(coords) <- coords$Cluster


path_df <- data.frame(
    X = coords[edgelist[, 1], "X"],
    Y = coords[edgelist[, 1], "Y"],
    X_end = coords[edgelist[, 2], "X"],
    Y_end = coords[edgelist[, 2], "Y"]
)

val_abun <- read.csv("/opt/megaseq-data/wcpilch/MMRF-ImmuneAtlas-Analysis-Sync/output/PAPER_FIGURES/Validation/Individual_Risk/Diff_Abundance/LINEAR_LOGIT/RISK_CATEGORIES_STUDY_SITE/linear_reg_UNIcd8_only.csv", header = T) |>
    dplyr::filter(factor == "davies_based_riskhigh_risk") |>
    dplyr::select(cluster, coef) |>
    dplyr::rename(Cluster = "cluster")

X <- reducedDim(sce, "UMAP") |> as.data.frame()

colnames(X)[1:2] <- c("Dim1", "Dim2")
sds <- SlingshotDataSet(sce)



clusterLabels <- slingClusterLabels(sds)
connectivity <- slingMST(sds, as.df = T)

lineage_list <- unique(connectivity$Lineage)
lineage_counts <- connectivity |>
    dplyr::group_by(Lineage) |>
    dplyr::summarise(max_order = max(Order))
rownames(lineage_counts) <- lineage_counts$Lineage

path_df <- NULL

for (lin_idx in lineage_list) {
    tmp_connectivity <- connectivity |> dplyr::filter(Lineage == lin_idx)
    max_order <- unlist(lineage_counts[lin_idx, "max_order"]) - 1
    for (ord_idx in 1:max_order) {
        if (is.null(path_df)) {
            path_df <- data.frame(Cluster1 = tmp_connectivity[ord_idx, "Cluster"], Cluster2 = tmp_connectivity[ord_idx + 1, "Cluster"])
        } else {
            tmp_df <- data.frame(Cluster1 = tmp_connectivity[ord_idx, "Cluster"], Cluster2 = tmp_connectivity[ord_idx + 1, "Cluster"])
            path_df <- rbind(path_df, tmp_df)
        }
    }
}

path_df_simp <- path_df |> dplyr::distinct(Cluster1, Cluster2)

path_df_coords <- data.frame(
    X = coords[path_df_simp[, "Cluster1"], "X"],
    Y = coords[path_df_simp[, "Cluster1"], "Y"],
    X_end = coords[path_df_simp[, "Cluster2"], "X"],
    Y_end = coords[path_df_simp[, "Cluster2"], "Y"]
)



path_df_coords <- path_df_coords |> dplyr::mutate(
    angle = atan2(Y_end - Y, X_end - X),
    X_end_mod = X_end - 0.2 * cos(angle),
    Y_end_mod = Y_end - 0.2 * sin(angle)
)


clusters <- unique(connectivity$Cluster)
nclus <- length(clusters)
centers <- t(vapply(clusters, function(clID) {
    w <- clusterLabels[, clID]
    return(apply(X, 2, weighted.mean, w = w))
}, rep(0, ncol(X)))) # gets center of UMAP points
X <- X[rowSums(clusterLabels) > 0, , drop = FALSE]
clusterLabels <- clusterLabels[rowSums(clusterLabels) > 0, ,
    drop = FALSE
]

X$cellname <- rownames(X)
X <- dplyr::left_join(X, per_cell_cluster_info, by = "cellname")

centers <- centers |> as.data.frame()
centers$Cluster <- rownames(centers)

library(unikn)
# test <- pal_unikn_pair[1:14]
# test <- t(test)
# library(paletteer)

# palette <- paletteer_d("RColorBrewer::Spectral")
# palette <- c("#2f4f4f", "#a52a2a", "#228b22", "#4b0082", "#ff8c00", "#deb887", "#00ff00", "#00bfff", "#0000ff", "#ff00ff", "#ffff54", "#dda0dd", "#ff1493", "#7fffd4") # paletteer_d("ggthemes::Classic_Cyclic")
# palette <- colorRampPalette(palette)(14)
# set.seed(SEED_TESTING)
# palette <- permute(palette)




#     ggrastr::rasterize(geom_point(shape = 21, stroke = 0, size = 0.5, fill = X$color_sub, color = X$color_sub)) +

# geom_point(aes(fill = sce$ident), col = "grey70", shape = 21) +

mst_with_centers <- dplyr::left_join(connectivity, centers, by = "Cluster") |>
    dplyr::left_join(coords, by = "Cluster") |>
    dplyr::left_join(cluster_size, by = "Cluster")


centers <- mst_with_centers |> dplyr::distinct(Cluster, Dim1, Dim2, X, Y, `Cell Count`)
centers_nostart <- mst_with_centers |>
    dplyr::filter(Order != 1) |>
    dplyr::distinct(Cluster, Dim1, Dim2, X, Y, `Cell Count`)
centers_only_start <- mst_with_centers |>
    dplyr::filter(Order == 1) |>
    dplyr::distinct(Cluster, Dim1, Dim2, X, Y, `Cell Count`)

centers$subcluster_V03072023 <- centers$Cluster

centers_nostart$subcluster_V03072023 <- centers_nostart$Cluster
centers_only_start$subcluster_V03072023 <- centers_only_start$Cluster

centers <- centers |>
    dplyr::left_join(per_cluster_info, by = "subcluster_V03072023") |>
    dplyr::left_join(val_abun)
centers_nostart <- centers_nostart |> dplyr::left_join(per_cluster_info, by = "subcluster_V03072023")
centers_only_start <- centers_only_start |> dplyr::left_join(per_cluster_info, by = "subcluster_V03072023")

lin1_only <- dplyr::filter(mst_with_centers, Lineage == 1)
p <- ggplot(data = mst_with_centers, size = 6, aes(x = X, y = Y)) +
    theme_prism() +
    geom_segment(data = path_df_coords, aes(xend = X_end_mod, yend = Y_end_mod), arrow = arrow()) +
    geom_point(data = centers, aes(label = paste0(cellID_short), color = coef, fill = coef, size = `Cell Count`), color = "black", label.size = 0.35, shape = 21, show.legend = T) +
    geom_text(data = centers, aes(label = paste0(cellID_short), color = coef), label.size = 0.35, size = 5, vjust = 1, nudge_y = -.125) +
    scale_fill_gradient2(
        low = fill_NP, mid = "grey", high = fill_RP, limits = c(-0.21, 0.21),
        oob = squish
    ) +
    scale_color_gradient2(
        low = fill_NP, mid = "grey", high = fill_RP, limits = c(-0.21, 0.21),
        oob = squish
    ) +
    xlim(0.5, 4.2)

p <- p +
    # scale_x_continuous(expand = c(0, 0)) +
    # scale_y_continuous(expand = c(0, 0)) +
    # scale_x_reverse() +
    scale_y_reverse()

p <- p + theme(
    axis.line = element_blank(), axis.text.x = element_blank(),
    axis.text.y = element_blank(), axis.ticks = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.background = element_blank(), panel.border = element_blank(), panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), plot.background = element_blank()
) + guides(size = guide_legend(override.aes = list(colour = "grey", fill = "white")))



pdf_and_png(p, output_traj, "HR_UMAP_traj", pdfWidth = W_FULL * .75, pdfHeight = H_FULL, scale = 3)
```

```{r}
val_abun <- read.csv("/opt/megaseq-data/wcpilch/MMRF-ImmuneAtlas-Analysis-Sync/output/PAPER_FIGURES/Validation/Individual_Risk/Diff_Abundance/LINEAR_LOGIT/RISK_CATEGORIES_STUDY_SITE/linear_reg_UNIcd8_only.csv", header = T) |>
    dplyr::filter(factor == "mixed_nsd2_1q21_class: NSD2.Gain1q21 - Normal") |>
    dplyr::select(cluster, coef) |>
    dplyr::rename(Cluster = "cluster")


centers <- centers |>
    dplyr::select(-coef) |>
    dplyr::left_join(val_abun, by = "Cluster")
centers_nostart <- centers_nostart |> dplyr::left_join(per_cluster_info, by = "subcluster_V03072023")
centers_only_start <- centers_only_start |> dplyr::left_join(per_cluster_info, by = "subcluster_V03072023")

lin1_only <- dplyr::filter(mst_with_centers, Lineage == 1)
p <- ggplot(data = mst_with_centers, size = 6, aes(x = X, y = Y)) +
    theme_prism() +
    geom_segment(data = path_df_coords, aes(xend = X_end_mod, yend = Y_end_mod), arrow = arrow()) +
    geom_point(data = centers, aes(label = paste0(cellID_short), color = coef, fill = coef, size = `Cell Count`), color = "black", label.size = 0.35, shape = 21, show.legend = T) +
    geom_text(data = centers, aes(label = paste0(cellID_short), color = coef), label.size = 0.35, size = 5, vjust = 1, nudge_y = -.125) +
    scale_fill_gradient2(
        low = fill_NP, mid = "grey", high = fill_RP, limits = c(-0.21, 0.21),
        oob = squish
    ) +
    scale_color_gradient2(
        low = fill_NP, mid = "grey", high = fill_RP, limits = c(-0.21, 0.21),
        oob = squish
    ) +
    xlim(0.5, 4.2)

p <- p +
    # scale_x_continuous(expand = c(0, 0)) +
    # scale_y_continuous(expand = c(0, 0)) +
    # scale_x_reverse() +
    scale_y_reverse()

p <- p + theme(
    axis.line = element_blank(), axis.text.x = element_blank(),
    axis.text.y = element_blank(), axis.ticks = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.background = element_blank(), panel.border = element_blank(), panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), plot.background = element_blank()
) + guides(size = guide_legend(override.aes = list(colour = "grey", fill = "white")))

pdf_and_png(p, output_traj, "NSD2_1q21_UMAP_traj", pdfWidth = W_FULL * .75, pdfHeight = H_FULL, scale = 3)
```

```{r}
val_abun <- read.csv("/opt/megaseq-data/wcpilch/MMRF-ImmuneAtlas-Analysis-Sync/output/PAPER_FIGURES/Validation/Individual_Risk/Diff_Abundance/LINEAR_LOGIT/RISK_CATEGORIES_STUDY_SITE/linear_reg_UNIcd8_only.csv", header = T) |>
    dplyr::filter(factor == "tp53_inactivation_state: COMPLETE - NONE") |>
    dplyr::select(cluster, coef) |>
    dplyr::rename(Cluster = "cluster")


centers <- centers |>
    dplyr::select(-coef) |>
    dplyr::left_join(val_abun, by = "Cluster")
centers_nostart <- centers_nostart |> dplyr::left_join(per_cluster_info, by = "subcluster_V03072023")
centers_only_start <- centers_only_start |> dplyr::left_join(per_cluster_info, by = "subcluster_V03072023")

lin1_only <- dplyr::filter(mst_with_centers, Lineage == 1)
p <- ggplot(data = mst_with_centers, size = 6, aes(x = X, y = Y)) +
    theme_prism() +
    geom_segment(data = path_df_coords, aes(xend = X_end_mod, yend = Y_end_mod), arrow = arrow()) +
    geom_point(data = centers, aes(label = paste0(cellID_short), color = coef, fill = coef, size = `Cell Count`), color = "black", label.size = 0.35, shape = 21, show.legend = T) +
    geom_text(data = centers, aes(label = paste0(cellID_short), color = coef), label.size = 0.35, size = 5, vjust = 1, nudge_y = -.125) +
    scale_fill_gradient2(
        low = fill_NP, mid = "grey", high = fill_RP, limits = c(-0.21, 0.21),
        oob = squish
    ) +
    scale_color_gradient2(
        low = fill_NP, mid = "grey", high = fill_RP, limits = c(-0.21, 0.21),
        oob = squish
    ) +
    xlim(0.5, 4.2)

p <- p +
    # scale_x_continuous(expand = c(0, 0)) +
    # scale_y_continuous(expand = c(0, 0)) +
    # scale_x_reverse() +
    scale_y_reverse()

p <- p + theme(
    axis.line = element_blank(), axis.text.x = element_blank(),
    axis.text.y = element_blank(), axis.ticks = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.background = element_blank(), panel.border = element_blank(), panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), plot.background = element_blank()
) + guides(size = guide_legend(override.aes = list(colour = "grey", fill = "white")))

pdf_and_png(p, output_traj, "tp53_complete_v_none_UMAP_traj", pdfWidth = W_FULL * .75, pdfHeight = H_FULL, scale = 3)
```
