---
title: "Figure 5A - Summary of DEG and DAA Results"
author: "William Pilcher"
date: "`r Sys.Date()`"
output: 
    html_document:
        toc: true
        toc_float: true
---

Revisions: Code is reformatted. Abundance data is precomputed in the prior differential abundance code results. 

Box plots dropped as a supplemental figure on revisions to simplify supplemental documents following expanded risk analysis

```{r setup, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

# Loading Data and Setting Up Options
```{r init}
source("source/Validation/validation_load_data.R", local = T)
merged <- merged |> subset(cohort == "discovery")

output_corr <- file.path(output, "Fig5", "Cluster_Signatures")
dir.create(output_corr, recursive = T, showWarnings = F)
```

# Setup counts object
```{r}
baseline <- merged |> subset(VJ_INTERVAL == "Baseline" & lineage_group != "LQ")
rm(merged)
gc()
```

# Compute Signatures defined in Supplemental Table 4

```{r} 
library(UCell)

signature_list <- c(list(
    # Dysfunctional signature, updated to include some positive and negative elements.
    "Dysfunctional" = c("B3GAT1+", "ZEB2+", "KLRG1+", "KLRK1+", "TIGIT+", "PDCD1+", "LAG3+", "CTLA4+", "HAVCR2+", "TOX+", "CD160+", "CD27-", "CD28-"),

    # Previous IFN signature, not used
    "IFN" = c("IFI6", "IFI30", "IFITM3", "IFI44L", "IFITM2", "S100A4", "IFI16", "ISG15", "STAT1", "IFI44", "STAT2", "APOL6", "IFIT3", "IFI35", "IFIT2", "JAK2", "IFI27L2", "GBP1", "GBP2", "IFIT1", "IFIH1", "IFITM1", "GBP4", "IFI27", "ISG15", "MX1", "OAS1", "XAF1", "APOL3", "IFIT5", "IFNG"),
    "HLA" = c("HLA-DRA", "CD74", "HLA-DRB1", "CD52", "HLA-DPB1", "HLA-DPA1", "HLA-DRB5", "HLA-DQB1", "HLA-DMA", "HLA-DQA1", "HLA-DOA"),
    "SASP" = c("ACVR1B", "ANG", "ANGPT1", "ANGPTL4", "AREG", "AXL", "BEX3", "BMP2", "BMP6", "C3", "CCL1", "CCL13", "CCL16", "CCL2", "CCL20", "CCL24", "CCL26", "CCL3", "CCL3L1", "CCL4", "CCL5", "CCL7", "CCL8", "CD55", "CD9", "CSF1", "CSF2", "CSF2RB", "CST4", "CTNNB1", "CTSB", "CXCL1", "CXCL10", "CXCL12", "CXCL16", "CXCL2", "CXCL3", "CXCL8", "CXCR2", "DKK1", "EDN1", "EGF", "EGFR", "EREG", "ESM1", "ETS2", "FAS", "FGF1", "FGF2", "FGF7", "GDF15", "GEM", "GMFG", "HGF", "HMGB1", "ICAM1", "ICAM3", "IGF1", "IGFBP1", "IGFBP2", "IGFBP3", "IGFBP4", "IGFBP5", "IGFBP6", "IGFBP7", "IL10", "IL13", "IL15", "IL18", "IL1A", "IL1B", "IL2", "IL32", "IL6", "IL6ST", "IL7", "INHA", "IQGAP2", "ITGA2", "ITPKA", "JUN", "KITLG", "LCP1", "MIF", "MMP1", "MMP10", "MMP12", "MMP13", "MMP14", "MMP2", "MMP3", "MMP9", "NAP1L4", "NRG1", "PAPPA", "PECAM1", "PGF", "PIGF", "PLAT", "PLAU", "PLAUR", "PTBP1", "PTGER2", "PTGES", "RPS6KA5", "SCAMP4", "SELPLG", "SEMA3F", "SERPINB4", "SERPINE1", "SERPINE2", "SPP1", "SPX", "TIMP2", "TNF", "TNFRSF10C", "TNFRSF11B", "TNFRSF1A", "TNFRSF1B", "TUBGCP2", "VEGFA", "VEGFC", "VGF", "WNT16", "WNT2"),
    "Naive" = c("IL7R", "CCR7", "SELL", "FOXO1", "KLF2", "KLF3", "LEF1", "TCF7", "ACTN1", "FOXP1", "BTG1", "BTG2", "TOB1", "FOXO1"),
    "Cytotoxic" = c("GZMA", "GZMB", "GZMH", "GZMK", "GZMH", "GNLY", "PRF1", "IFNG", "TNF", "SERPINB1", "SERPINB6", "SERPINB9", "CTSA", "CTSB", "CTSC", "CTSD", "CTSW", "CST3", "CST7", "CSTB", "LAMP1", "LAMP3", "CAPN2", "GZMM", "CTSH", "CAPN2", "PLEK"),
    "Exhausted" = c("PDCD1", "LAYN", "HAVCR2", "LAG3", "CD244", "CTLA4", "LILRB1", "TIGIT", "TOX", "VSIR", "BTLA", "ENTPD1", "CD160", "LAIR1"),
    "IFNA" = c(
        "IFI44L",
        "ISG15",
        "XAF1",
        "IFI6",
        "MX1",
        "LY6E",
        "EIF2AK2",
        "STAT1",
        "MX2",
        "IFIT3",
        "ISG20",
        "OAS1",
        "IFI44",
        "IRF7",
        "IFIT1",
        "OAS3",
        "IFI35",
        "OAS2",
        "IFI27"
    )
))
```

```{r}
# tmp <- baseline |> subset(subcluster_V03072023 == "NkT.0")
baseline <- AddModuleScore_UCell(baseline, features = signature_list, name = "")
```


```{r}
# For outcome sections, focussing on the non-plasma, non-erythroid subset (Immune) for summary figures.
types_list <- list(
    "CD3+ Cells" = c("CD8", "CD4"),
    "Myeloid Cells" = "M",
    "B Cells" = "B",
    "CD8+" = "CD8",
    "CD4+" = "CD4",
    "Nk" = "Nk",
    "Immune" = c("CD8", "CD4", "M", "B", "Other", "Nk"),
    "All_NoPlasma" = c("CD8", "CD4", "M", "B", "Other", "Nk", "E"),
    "All" = c("CD8", "CD4", "M", "B", "Other", "Nk", "P", "E")
)
idx_name <- "Immune"

averageMod <- baseline@meta.data %>%
    dplyr::group_by(subcluster_V03072023) %>%
    dplyr::summarise(
        "NaiveT" = mean(Naive),
        "CytotoxicT" = mean(Cytotoxic),
        "ExhaustedT" = mean(Exhausted),
        "DysfunctionalT" = mean(Dysfunctional),
        "SASP" = mean(SASP),
        "IFN1" = mean(IFNA),
        "HLA" = mean(HLA)
    ) |>
    gather(Module, Score, -subcluster_V03072023) |>
    as.data.frame()

diff_expr <- averageMod

cluster_info <- dplyr::distinct(baseline@meta.data, subcluster_V03072023, cellID_short, lineage_group, lineage_order)
diff_expr <- dplyr::left_join(diff_expr, cluster_info)
diff_expr <- diff_expr |> arrange(subcluster_V03072023)
diff_expr$cellID_short <- factor(diff_expr$cellID_short, levels = unique(diff_expr$cellID_short))
diff_expr <- diff_expr |> dplyr::filter(lineage_group != "E", lineage_group != "P", lineage_group != "LQ")


diff_expr_test <- diff_expr |>
    group_by(Module) |>
    dplyr::mutate(mean_module = mean(Score), var_module = var(Score), z = (Score - mean_module) / sd(Score), min_max = 2 * ((Score - min(Score)) / max(Score - min(Score)) - 0.5))

diff_expr_test$Module <- factor(diff_expr_test$Module, levels = rev(c(
    "NaiveT",
    "CytotoxicT",
    "ExhaustedT",
    "DysfunctionalT",
    "SASP",
    "IFN1",
    "HLA"
)))
cellID_short_ordering <- readRDS("data/cellID_short_figure_ordering.RDS")

diff_expr_test$cellID_short <- factor(diff_expr_test$cellID_short, levels = cellID_short_ordering)

diff_expr_test$lineage_group <- factor(diff_expr_test$lineage_group, levels = c("CD8", "CD4", "M", "B", "Other", "Nk"))

expr_plot_list <- list()
for (i in types_list[[idx_name]]) {
    tmp_expr <- diff_expr_test |> dplyr::filter(lineage_group == i)
    expr_plot_list[[i]] <- ggplot(tmp_expr) +
        geom_tile(aes(x = cellID_short, y = Module, fill = z), color = "black", lwd = 0.6, linetype = 1) +
        scale_fill_gradient2(
            low = "#1d9ae3",
            high = "#f63575",
            limits = range(c(-3, 3)),
            oob = squish
        ) +
        theme_prism() +
        coord_fixed(ratio = 1) +
        xlab("") +
        ylab("") +
        theme(
            axis.text.x = element_text(
                size = 14 * 0.95,
                family = "sans", face = "bold",
                margin = margin(t = 0.8 * 14 / 4),
                angle = 90,
                vjust = 0.5,
                hjust = 1,
            ),
            plot.margin = margin(
                14 / 2, 14 / 2,
                0, 14 / 2
            ),
            legend.position = "top"
        ) +
        # element_text(
        #     angle = 90,
        #     vjust = 0.5, hjust = 1,
        # )) +
        guides(size = guide_legend(override.aes = list(shape = 21, colour = "grey", fill = "white")), legend.position = "top")
    if (i != types_list[[idx_name]][[1]]) {
        expr_plot_list[[i]] <- expr_plot_list[[i]] + theme(
            axis.text.y = element_blank(),
            axis.ticks.y = element_blank(),
            axis.title.y = element_blank(),
            axis.line.y = element_blank(),
            axis.ticks.length.y = unit(0, "lines")
        )
    }
}

plot_expr <- patchwork::wrap_plots(c(expr_plot_list), nrow = 1, ncol = length(types_list[[idx_name]]), byrow = T, guides = "collect", axes = "collect", axes_titles = "collect")

pdf_and_png(plot_expr, output_corr, paste0("TEST_Lower_Panel_Sig_Score_No_Abundance"), pdfWidth = 8, pdfHeight = 2.4, scale = 2.5)
```

```{r}
cellID_short_ordering <- readRDS("data/cellID_short_figure_ordering.RDS")



top_plot_info <- read.csv("/opt/megaseq-data/wcpilch/MMRF-ImmuneAtlas-Analysis-Sync/output/PAPER_FIGURES/Validation/Individual_Risk/Diff_Abundance/LINEAR_LOGIT/RISK_CATEGORIES_STUDY_SITE/linear_reg_UNIimmune_only.csv", header = T, row.names = 1) |>
    dplyr::filter(factor %in% c("davies_based_riskhigh_risk", "progression_group: RP - NP", "SR_davies.progression_group: standard_risk.RP - standard_risk.NP", "SR_davies.progression_group: high_risk.RP - high_risk.NP"))
top_plot_list <- list()

top_plot_info <- top_plot_info |> dplyr::mutate(variable_name = dplyr::case_when(
    factor == "davies_based_riskhigh_risk" ~ "HR vs SR",
    factor == "progression_group: RP - NP" ~ "RP vs NP",
    factor == "SR_davies.progression_group: standard_risk.RP - standard_risk.NP" ~ "SR: RP vs NP",
    factor == "SR_davies.progression_group: high_risk.RP - high_risk.NP" ~ "HR: RP vs NP",
))

cluster_md <- baseline@meta.data |> dplyr::distinct(subcluster_V03072023, isDoublet, subcluster_V03072023_compartment, lineage_group, lineage_order, cellID_short, cellID_long)
cluster_md$cluster <- cluster_md$subcluster_V03072023
top_plot_info <- dplyr::left_join(top_plot_info, cluster_md, by = "cluster")

top_plot_info <- top_plot_info |> dplyr::mutate(binned_pval = dplyr::case_when(
    p.val < 0.001 & coef > 0 ~ "Enriched (<0.001)",
    p.val < 0.01 & coef > 0 ~ "Enriched (<0.01)",
    p.val < 0.05 & coef > 0 ~ "Enriched (0.05)",
    p.val < 0.001 & coef < 0 ~ "Depleted (<0.001)",
    p.val < 0.01 & coef < 0 ~ "Depleted (<0.01)",
    p.val < 0.05 & coef < 0 ~ "Depleted (0.05)",
    .default = "NS"
))

top_plot_info$binned_pval <- factor(top_plot_info$binned_pval, levels = c(
    "Depleted (<0.001)", "Depleted (<0.01)", "Depleted (0.05)", "NS", "Enriched (0.05)", "Enriched (<0.01)", "Enriched (<0.001)"
))



top_plot_info <- top_plot_info |> dplyr::mutate(sig_levels = dplyr::case_when(
    p.val < 0.01 ~ "Significant (p<0.01)",
    p.val < 0.05 ~ "Significant (p<0.05)",
    .default = "NS"
))

top_plot_info$sig_levels <- factor(top_plot_info$sig_levels, levels = c(
    "NS", "Significant (p<0.05)", "Significant (p<0.01)"
))

top_plot_info$p.val <- as.numeric(top_plot_info$p.val)
top_plot_info$coef <- as.numeric(top_plot_info$coef)


lineage_group_names_df <- data.frame(
    lineage_group = c("CD8", "CD4", "M", "B", "Other", "Nk", "E"),
    lineage_group_name = c("CD8+ T Cell", "CD4+ T Cell", "Myeloid", "B Cell", "Other", "Nk Cell", "Erythroid")
)
rownames(lineage_group_names_df) <- lineage_group_names_df$lineage_group

top_plot_info$cellID_short <- factor(top_plot_info$cellID_short, levels = cellID_short_ordering)

top_plot_info$variable_name <- factor(top_plot_info$variable_name, levels = rev(c(
    "HR vs SR",
    "RP vs NP",
    "SR: RP vs NP",
    "HR: RP vs NP"
)))

for (i in types_list[[idx_name]]) {
    lineage_group_name <- lineage_group_names_df[i, "lineage_group_name"]
    sub_wilcox_out <- top_plot_info |> dplyr::filter(lineage_group %in% i)

    sub_wilcox_out$sig_binned_value <- factor(sub_wilcox_out$binned_pval, levels = c(
        "NS", "Significant (p<0.05)", "Significant (p<0.01)"
    ))

    top_plot_list[[i]] <- ggplot(sub_wilcox_out) +
        geom_point(aes(x = cellID_short, y = variable_name, fill = coef, size = sig_levels, shape = sig_levels), color = "#868686", show.legend = TRUE) +
        scale_fill_gradient2(
            low = fill_NP, mid = "grey", high = fill_RP, limits = c(-0.31, 0.31),
            oob = squish
        ) +
        scale_size_manual(values = c("Significant (p<0.01)" = 7.5, "Significant (p<0.05)" = 6, "NS" = 4.25), drop = F) +
        scale_shape_manual(values = c("Significant (p<0.01)" = 22, "Significant (p<0.05)" = 23, "NS" = 21), drop = F) +
        theme_prism() +
        xlab("Cluster") +
        ylab("") +
        ggtitle(lineage_group_name) +
        guides(size = guide_legend(override.aes = list(colour = "grey", fill = "white"), ncol = 1, byrow = T)) +
        theme(
            axis.text.x = element_blank(),
            axis.ticks.x = element_blank(),
            axis.title.x = element_blank(),
            # axis.line.x = element_blank(),
            plot.margin = unit(c(0, 1, 0, 0), "lines"),
            legend.position = "top"
        )
    if (i != types_list[[idx_name]][[1]]) {
        top_plot_list[[i]] <- top_plot_list[[i]] + theme(
            axis.text.y = element_blank(),
            axis.ticks.y = element_blank(),
            axis.title.y = element_blank(),
            axis.line.y = element_blank(),
            axis.ticks.length.y = unit(0, "lines")
        )
    }

    top_plot_list[[i]] <- top_plot_list[[i]] + coord_fixed()
}
plot <- patchwork::wrap_plots(c(top_plot_list), nrow = 1, ncol = length(types_list[[idx_name]]), byrow = T, guides = "collect", axes = "collect", axes_titles = "collect")
plot_both <- patchwork::wrap_plots(c(top_plot_list, expr_plot_list), nrow = 2, ncol = length(types_list[[idx_name]]), byrow = T, guides = "collect", axes = "collect", axes_titles = "collect") & theme(legend.position = "bottom", legend.direction = "vertical")

pdf_and_png(plot, output_corr, paste0("TEST_UPPER_Panel_Abundance"), pdfWidth = 8, pdfHeight = 2, scale = 2.5)

pdf_and_png(plot_both, output_corr, paste0("TEST_combined_panel_abundance"), pdfWidth = 8, pdfHeight = 3.2, scale = 2.5)
```
