---
title: "Slingshot with Myeloid Cells"
author: "William Pilcher"
date: "`r Sys.Date()`"
output: 
    html_document:
        toc: true
        toc_float: true
---


# Setup
```{r init}
source("source/Figure_3/Fig3_standard_load_data.R", local = T)
output <- file.path("/opt/pmedseq-data/wcpilch/Projects/MMRF-ImmuneAtlas-Annotation/output", "monocle3_myeloid")
dir.create(output, showWarnings = F, recursive = T)
```

# Create Baseline CD8
Multiple baseline samples are possible, verify
```{r baseline_objects}
gc()
myeloid <- subset(merged, subset = (
    lineage_group == "M" &
        isDoublet %in% c("Singlet")))

rm(merged)
rm(merged_md_bckup)
rm(clusterMD)
gc()

# BEry <- subset_and_markers(BEry, name = "cd8-only-alltimepoints-BEry", output = output, SKIP_MARKERS = T, DIMPLOT_ADDITIONAL_DISPLAY = "seurat_clusters_compartment_1_20_23_fullname", res = NULL, rebuildObject = F)
```


# SlingShot 
```{r}
myeloid <- subset_and_markers(myeloid, name = paste0("CORRECTED_myeloid_30pcs_noLQ_", 30), output = output, SKIP_MARKERS = T, DIMPLOT_ADDITIONAL_DISPLAY = cluster_group, res = NULL, rebuildObject = F, dims = 30)
myeloid[["umap_new"]] <- myeloid[["umapsub"]]
myeloid[["umap"]] <- myeloid[["umap.sub"]]

library(slingshot)
library(SingleCellExperiment)
library(Polychrome)
library(BUSpaRse)
library(tidyverse)
library(tidymodels)

# outputs format: TrajectoryObject, TrajectoryLines, numLineages, AllGenes, TopGenes, validation results
outputs <- runSlingshot(myeloid, groupingVar = "subcluster_V03072023", output = output, nameMod = "CORRECTED_myeloid_alltimepoints_m10start_noLQ", slingshotDim = "HARMONY", visualizationDim = "UMAP", startCluster = "Myeloid.10", CREATE_SUBFOLDER_WITH_NAMEMOD = T, REBUILD_TRAJECTORY = F)
```

```{r}
sce <- outputs[["TrajectoryObject"]]

source("/opt/pmedseq-data/wcpilch/Projects/MMRF-ImmuneAtlas-Annotation/source/general_slingshot.R", chdir = T)

pdf_and_png(plotLineages(test, pseudotimeLineage = "AVG"), output, "avgPseudo", pdfWidth = 12, pdfHeight = 7)

out <- plotOrderedDensity(test, output = output, nameMod = "test")
write.csv(out[["ordering"]] |> as.data.frame(), file.path(output, "ordering.csv"))
```

```{r}

```